git action debug

diff --git a/.github/workflows/ubi-api-core-ci-action.yml b/.github/workflows/ubi-api-core-ci-action.yml
--- a/.github/workflows/ubi-api-core-ci-action.yml
+++ b/.github/workflows/ubi-api-core-ci-action.yml
@@ -27,35 +27,35 @@ jobs:
             description: "Set the last process exit value"
             value: ${{ steps.integration-test.outputs.integration_test_result }}
 
-        run: >
-          sh deploy.sh -t true
-          export TEST_RESULT=$?
-          echo "::set-output name=integration_test_result::${TEST_RESULT}"
+#        run: >
+#          sh deploy.sh -t true
+#          export TEST_RESULT=$?
+#          echo "::set-output name=integration_test_result::${TEST_RESULT}"
 
-  build-docker:
-    # —— Setup Docker Environment 🐋 —————————————————————————————————————————————
-    needs: integration-test
-    runs-on: ubuntu-latest
-
-    steps:
-      # —— Setup GitHub Actions 🐙 —————————————————————————————————————————————
-      - name: Cancel if test failed
-        # If the test failed will execute this job otherwise will cancel it
-        if: ${{ needs.integration-test.outputs.git_pr_sha == 1' }}
-        uses: andymckay/cancel-action@0.2
-
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DEV_DOCKER_ACCOUNT_ID }}
-          password: ${{ secrets.DEV_DOCKER_ACCOUNT_PASSWORD }}
-
-      - name: Build and push Docker image created with the Dockerfile
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
-          push: true
-          tags: nestorcolt/ubi-api-core:latest
+#  build-docker:
+#    # —— Setup Docker Environment 🐋 —————————————————————————————————————————————
+#    needs: integration-test
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      # —— Setup GitHub Actions 🐙 —————————————————————————————————————————————
+#      - name: Cancel if test failed
+#        # If the test failed will execute this job otherwise will cancel it
+#        if: ${{ needs.integration-test.outputs.git_pr_sha == 1' }}
+#        uses: andymckay/cancel-action@0.2
+#
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#
+#      - name: Login to DockerHub
+#        uses: docker/login-action@v1
+#        with:
+#          username: ${{ secrets.DEV_DOCKER_ACCOUNT_ID }}
+#          password: ${{ secrets.DEV_DOCKER_ACCOUNT_PASSWORD }}
+#
+#      - name: Build and push Docker image created with the Dockerfile
+#        id: docker_build
+#        uses: docker/build-push-action@v2
+#        with:
+#          push: true
+#          tags: nestorcolt/ubi-api-core:latest
